version: '3'

services:

  saltmaster-gui:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.master-gui
      args:
        SALT_MAJOR_VERSION: 3006
    container_name: saltmaster
    hostname: saltmaster
    ports:
      - 4505:4505
      - 4506:4506
      - 3333:3333
# OPTIONAL VOLUMES FOR TESTING httpd INSTALL
#    volumes:
#    - ./srv/:/srv/
#    - ./conf/master/:/etc/salt/master.d/

#  saltmaster-no-gui:
#    build:
#      context: ./dockerfiles
#      dockerfile: Dockerfile.master
#      args:
#        SALT_VERSION: 3006
#    container_name: saltmaster
#    hostname: saltmaster
#    ports:
#      - 4505:4505
#      - 4506:4506
#    volumes:
#    - ./srv/:/srv/
#    - ./conf/master/:/etc/salt/master.d/

  saltminion-ubuntu:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.minion.ubuntu
      args:
        SALT_MAJOR_VERSION: 3006
    container_name: saltminion-ubuntu
    hostname: saltminion-ubuntu
    depends_on:
      - saltmaster-gui
      #- saltmaster-no-gui
    restart: on-failure

  saltminion-centos:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.minion.centos
      args:
        SALT_MAJOR_VERSION: 3006
    container_name: saltminion-centos
    hostname: saltminion-centos
    depends_on:
      - saltmaster-gui
      #- saltmaster-no-gui
    restart: on-failure
